### ISSUE TITLE
Header manipulation

### ISSUE THREAD

**Issue by t2YU2m8l83** [dangkyokhoang/Man-in-the-Middle#1]
I'd like to see the option to edit request/response header values. If possible even with js functions to set random values. One example would be a random "X-Forwarded-For" value to get a "different IP" every request and another to change the google.com request url to google.co.jp.

**Comment by dangkyokhoang** [comment]
In the next version, which will be released in about two weeks, you'll be able to modify request and response headers (and also response data). Modifying request with user script is under consideration.
However, changing request headers doesn't change your location. If you want to change Google search location, go to Google > Settings > Search settings > Region settings. If you want to appear in some location, you might want to use a VPN or a proxy server.

**Comment by t2YU2m8l83** [comment]
I know that it doesn't change my location, but most geoblocked sites I ran into accept the "X-Forwarded-For" tag and let me pass. The random generated address let me bypass a bot protection on a site I frequently visit. I'm simply to fast for it ¯\\_(ツ)_/¯

**Comment by dangkyokhoang** [comment]
K. You'll probably be able to modify headers with your custom scripts in the next version.

**Comment by dangkyokhoang** [comment]
2.2 released. You're now able to modify request and response headers, but not request or response body.

**Comment by t2YU2m8l83** [comment]
Works fine, thank you ^^
Still now im stuck with the limitation of matching patterns. I've created another request in regards to that problem.
