### ISSUE TITLE
Disabled rules are still checked.

### ISSUE THREAD

**Issue by JaapKool** [dangkyokhoang/Man-in-the-Middle#11]
When you have some rules disabled, they are still checked if they should be used or not. First, the "Origin URL filters" are checked, and later if the rule is enabled or not.
When you do a lot of requests to a site which applies to a rule which which is disabled, the browser will be slow down because the string compare is still done. 
My suggestion is to do the enabled check first, and do the check for the  "Origin URL filters" later.

**Comment by dangkyokhoang** [comment]
Disabled rules aren't registered with the browser hence there's no performance concerns anyway.

See the method `Rule.setEnabled()` for this. When a rule is disabled, it also gets deactivated.
https://github.com/dangkyokhoang/Man-in-the-Middle/blob/9bbe092f425514e72388e7c73e5d229b4a35e154/src/page/background/js/class/Rule.js#L111
Other methods, child methods may only reactivate a rule if it's required to apply rule changes but not activate or deactivate the rule.
