### ISSUE TITLE
Intercepting response not working in Chrome

### ISSUE THREAD

**Issue by therisingindian** [dangkyokhoang/Man-in-the-Middle#12]
Response rules not working in Chrome.
<img width="1662" alt="issue" src="https://user-images.githubusercontent.com/22546257/50725031-a86a0e00-10f7-11e9-9887-a4fc5fbb963e.png">
<img width="1175" alt="google" src="https://user-images.githubusercontent.com/22546257/50725061-0d256880-10f8-11e9-91fc-52e036aea2ff.png">

**Comment by dangkyokhoang** [comment]
It's a known issue: https://github.com/dangkyokhoang/Man-in-the-Middle/projects/1#card-15622712

Chrome doesn't support response filter hence response rules don't work.

**Comment by therisingindian** [comment]
Thanks!
