### ISSUE TITLE
Intercepting responses for url fired from an application not working

### ISSUE THREAD

**Issue by therisingindian** [dangkyokhoang/Man-in-the-Middle#13]
Ex: I set rule to modify response for google.com to say Hello. This works when hit directly from the address bar. If I hit this url from an Angular or any other application as a GET request, I see the request in Network tab with the real response and not mocked response.

**Comment by dangkyokhoang** [comment]
The Network tool and the View-source tool always show original response data as well as response headers.

- The Network tab shows
  ![Man in the Middle - Modifying response](https://user-images.githubusercontent.com/14311741/50791740-50005f80-12f5-11e9-9df4-0b6aef225cdf.png)
- The actual text we get
  ![Man in the Middle - Modifying response](https://user-images.githubusercontent.com/14311741/50791798-73c3a580-12f5-11e9-816f-95cf08d530c7.png)

If I misunderstand something, please give me some more info about the case.

**Comment by therisingindian** [comment]
Since my application is receiving 401 status code, my intercepted response is not working. I even tried changing the header but didn't work. Is it possible to stop the request and redirect from the interceptor so that we don't see it in Network tab?

**Comment by dangkyokhoang** [comment]
Is this what you mean?
`Your app -> Request -> If 401 then Block`

**Comment by therisingindian** [comment]
Your app -> Request -> If it is available in the interceptor -> Don't fire request and use the mocked response.

**Comment by dangkyokhoang** [comment]
So what you're asking is perhaps not about the extension but about Angular HttpInterceptor? Though I've never used Angular, after reading [this SO question](https://stackoverflow.com/questions/48048564/angular-http-client-interceptor-not-working-when-returning-custom-observable) - which you might find useful, I think it could be something like this:
```` TypeScript
return Observable.of(new HttpResponse<any>({ body: 'Hello' }));
````

**Comment by therisingindian** [comment]
Thanks for this! I was trying if I can extend the extension to intercept the response without being fired. Is it possible to do so using Mozilla APIs, as an application cannot get the intercepted response.

**Comment by dangkyokhoang** [comment]
I don't really understand / know much about your case. However, if requests are canceled right from inside the application, there's no way for the browser to catch them (as they're actually not sent). If that's the case, you might want to use [Content Scripts](https://github.com/dangkyokhoang/Man-in-the-Middle#content-scripts) instead. Something like this:
![Man in the Middle - Content Script - Inject JavaScript](https://user-images.githubusercontent.com/14311741/50835063-41af5380-1388-11e9-982b-7388e926faff.png)

If further help's needed, you may still continue to comment on this issue or message me via [my Facebook](https://www.facebook.com/dangkyokhoang).
