### ISSUE TITLE
Unreliable for background tabs

### ISSUE THREAD

**Issue by t2YU2m8l83** [dangkyokhoang/Man-in-the-Middle#14]
Opening multiple background tabs that automatically load their page will result in random tabs failing to be injected with content scripts. With the following rules and link you can test this. Simply open multiple tabs through the mouseweel button and wait until all are finished loading. Then cycle through them and you'll notice that some have no image dispalyed until you reload the page.

Example page: https://9gag.com/darkhumor
Example scripts and rules:
![jquerry](https://user-images.githubusercontent.com/38610659/51086639-e80ca780-1740-11e9-886a-278ef733c31c.jpg)
![9gaga-script](https://user-images.githubusercontent.com/38610659/51086638-e7741100-1740-11e9-9fd7-91fad4330439.jpg)

script from the 9gag rule:
```
$("article[id^='jsid-post-']").each(function(index){
		var idParts = $(this).attr('id').split('-');
		var imageLink = "https://img-9gag-fun.9cache.com/photo/" + idParts[idParts.length - 1] + "_700b.jpg";
		$('.post-container .nsfw-post', this).empty();
		$('.post-container .nsfw-post', this).prepend("<img src='" + imageLink + "'/>");
});

$(window).scroll(function() {
	if($(this).scrollTop() % 900 <= 20){
		$("article[id^='jsid-post-']").each(function(index){
			var idParts = $(this).attr('id').split('-');
			var imageLink = "https://img-9gag-fun.9cache.com/photo/" + idParts[idParts.length - 1] + "_700b.jpg";
			$('.post-container .nsfw-post', this).empty();
			$('.post-container .nsfw-post', this).prepend("<img src='" + imageLink + "'/>");
		});
	}
});
```

optional css:
```
#gdpr iframe,
	.gdpr .btn-container a.red + .grey,
	.gdpr .btn-container a.blue,
	.post-container .nsfw-post h3,
	.post-container .nsfw-post p{
		display: none !important;
	}
	
	.post-container .nsfw-post {
		height: auto !important;
		border: 5px red solid !important;
	}

	.gdpr .btn-container a.blue + .grey {
		background-color: #09f !important;
		color: white !important;
	}

	.gdpr .btn-container a.red {
		background-color: #09f !important;
	}
```

**Comment by dangkyokhoang** [comment]
What do you mean by "tab"? As per "open multiple tabs through the mouseweel", maybe it's a post? I've tested, 800 posts and all the images are loaded.
![Man in the Middle - Inject JavaScript and CSS into pages](https://user-images.githubusercontent.com/14311741/51087247-465a7a00-1783-11e9-91c2-45d8392ae6a5.png)

The script should only be injected once, when the page first loads. If some images are loaded, then the script must have been injected to the page.

**Comment by t2YU2m8l83** [comment]
If you press the mouseweel button on a hyperlink it will be opened in a new tab. When I'm opening multiple tabs this way some fail to receive the injected scripts. This problem specifically occures because of the tabs opening without focus in the background and preload the webpage before I actually click on the tab to view the page. To test this, you should open NSFW images in new tabs.

**Comment by dangkyokhoang** [comment]
Thanks. I now understand. However the extension works just fine.

---
The problem is caused by early jQuery injection. If you open the options page's console, you'll see error logs:
````
Error: d is undefined      options.js:16:20 <- jQuery error
Error: $ is not defined    options.js:16:20 <- error <- no jQ available
````
---
To see what happens, I've used the uncompressed version of jQ 3.3.1;

prepend jQ with this line:
````javascript
console.log('start', 'window.document =', window.document);
````
and insert these lines at the beginning of `function assert` in the jQ code:
````javascript
console.log('function assert', 'window = ', window);
console.log('function assert', 'window.document = ', window.document);
console.log('function assert', 'document = ', document);
````
and surprisingly this is what I get for tabs where jQ runs into errors:
![Man in the Middle - Inject JavaScript to 9GAG](https://user-images.githubusercontent.com/14311741/51090660-dfa08500-17b1-11e9-9ecc-1c0f6ddd9882.png)
Though `window.document` is available from the start, the **var** `document` is somehow `undefined` inside `function assert`.

You should therefore report this issue to the jQuery team. Meanwhile, set the `DOM event` to `Loaded` for stability.
