### ISSUE TITLE
Remove button - doesn't remove entries in Content Scripts

### ISSUE THREAD

**Issue by CodeGenIQ** [dangkyokhoang/Man-in-the-Middle#15]
Hi I just downloaded the addon, and clicked on "Add" under Content Scripts.  
I clicked 3 times without typing anything, It added 3 entries.   

When expanding each entry and clicking "Remove" nothing happens

![image](https://user-images.githubusercontent.com/20977409/53652794-af089380-3c17-11e9-86bc-0c39ea2dc8c0.png)

**Comment by dangkyokhoang** [comment]
To remove a rule, you need to double-click the Remove button. This is an intended behavior as removing a rule is (currently) irreversible.
