### ISSUE TITLE
Optional Regex group returns undefined

### ISSUE THREAD

**Issue by t2YU2m8l83** [dangkyokhoang/Man-in-the-Middle#16]
If I declare an optional regex group it will return "undefined" instead of an empty string in case it doesn't match. The desired behaviour should be an empty string, otherwise optional groups would be useless.

**Comment by dangkyokhoang** [comment]
Updating. Thanks.

**Comment by dangkyokhoang** [comment]
Updated. Please update your extension to see if it works.

**Comment by t2YU2m8l83** [comment]
Works fine now. Thank you.
