### ISSUE TITLE
Naming rules

### ISSUE THREAD

**Issue by t2YU2m8l83** [dangkyokhoang/Man-in-the-Middle#2]
Rules should recive a description/name filed that is displayed in the overview list.

**Comment by dangkyokhoang** [comment]
Is this what you meant?
![Firefox Extension: Man in the Middle](https://lh3.googleusercontent.com/lasGWhGVYeUSDoRKXqNXRA2J-KQFNlKc5LLXZRcGIxCLFZA-QALyQg4dhTu3FTDt6IJp8Os67qQ0EtYZXt0TtwHIN5Z9mdA2aaspTDHg9SQBMc8UHmXH1cvJiBv8iR_USysF_q3a_Hl6LAwYMz_JRGADnC2yw6v5MRSNNGhHr6VWAQLmeoNDhsyCk6dHEP1905UF2-VXJQatTcxli1eO-n84BsVBEJo5OUpmfbzlsbiWY1whvwa-frh8Kw37R9h1fgkMshCUJneFxykrb33-iEbfcI223BghtZJREzmrGc3bAWGolBhrkTc9T6Na_4m696DebFuyvWKwFQ9qb16QiwdneHnMEVHYVcODUn1h5oyCaTiJTo0L_SI5WvlufAyQxY_gbHZFv9fMhAoYgEl4MRGq9Hzho2BbMSC42jCt5Z_NVKUYW-7PR7LcNJpX3rrbGe57vBdxY3axw4AOZPDyRj7YcUB_86eapUsZh3wR2KhppB9oimOHBDQ7Qt9GSSfXl2_9VnZw7K86MAIPv0DGN5F4mMkHYTpQrRcs9C97WlTkxZVzaz8LydV_RByyf6iQ0xtZ1X2cV8gf-52o6pmjs2DPnFOtOWPkC8IsVQQFSodZ0jAVNCTIlyvg4FeJmPQ=w688-h340-no)

**Comment by t2YU2m8l83** [comment]
Well yeah. I'd like a way to simply name the second rule "Facebook" and have all the fb domains included. While it might still be obvious what the rule with the facebook domain in the image does, with regular expressions and other special rule sets it would be handier to have a little info text instead of the first line displayed.

**Comment by dangkyokhoang** [comment]
I decided not to add a description field as in my view, rules are kinda set-and-forget (we don't get to see the rules often). But I do agree that having one would be somewhat useful 🤔 I really waver between adding or not.
Umm well I would like to keep this issue open. Is it ok?

**Comment by t2YU2m8l83** [comment]
The naming option is only an optional request on my side. While the header thing is a necessary addition for me to switch addons, descriptive names are only a nice to have. You can keep it open as long as you want.
