### ISSUE TITLE
Export/import rules

### ISSUE THREAD

**Issue by BorisNaguet** [dangkyokhoang/Man-in-the-Middle#21]
Hi,

I'd like to export a rule (maybe some people would prefer a list of rules), and import it.

I wanted to use your plugin to make some support, and ask a user to install it with a rule I'd write for him.
I haven't found a way to share rules with other people.

**Comment by dangkyokhoang** [comment]
You can inject a content script to the extension options page, which looks like this.

![Man in the Middle - Inject scripts to pages](https://user-images.githubusercontent.com/14311741/81034384-26dbe900-8ec1-11ea-8712-d692d6e62a90.png)

A short explanation of what the code does:
- Creates an `Export` button (1) for each rule.
- On (1) clicked, a script (2) will be logged to the console - which is what you share with others.
- To import the rule, open the options page's console and run the script (2).
- You can export several rules individually and combine the scripts (2) to get the single import script (simply concat them (2) all and rules will be imported individually).

Here's the code (you might minifiy it, for example, with https://skalman.github.io/UglifyJS-online/):
``` javascript
'use strict'

/* globals browser, Runtime, Collection */

const types = [
  'blockingRules',
  'headerRules',
  'responseRules',
  'contentScripts',
]

const [ main ] = document.getElementsByClassName('main')
const sections = types.map(type => document.getElementById(type))

if (!main || !sections.every(Boolean)) {
  throw Error('invalid page')
}

const importRules = rules => {
  const entries = Object.entries(rules)

  entries.forEach(([ type, rules ]) => rules.forEach(async rule => {
    const { id, enabled, sync } = await Runtime.sendMessage({
      sender: 'optionsPage',
      request: 'add',
      details: { type },
    })

    await Runtime.sendMessage({
      sender: 'optionsPage',
      request: 'modify',
      details: { type, id, change: rule },
    })

    Collection.create(type, { id, enabled, sync, ...rule })
  }))
}

const exportRules = rules => {
  const source = importRules.toString()
  // if source isn't minified, rule json should be beautified
  const ruleParam = JSON.stringify(rules, null, source.includes('  ') ? 2 : 0)
  const code = `(${ source })(${ ruleParam });`

  console.log(code)
}

const getProperties = rule => {
  // removes .id, .enabled, .sync from rule
  const { id, enabled, sync, ...properties } = rule

  return properties
}

const handleExportAll = async () => {
  const entries = await Promise.all(types.map(async type => [
    type,
    await browser.runtime.sendMessage({
      sender: 'optionsPage',
      request: 'getData',
      details: { type },
    })
  ]))
  const rules = Object.fromEntries(entries.map(([ type, rules ]) => [
    type,
    rules.map(rule => getProperties(rule)),
  ]))

  exportRules(rules)
}

const handleExport = async article => {
  const type = types[ sections.indexOf(article.closest('section[id]')) ]

  const articles = [ ...article.parentElement.children ]
  const index = articles.indexOf(article)

  if (index === -1) {
    return
  }

  const rules = await browser.runtime.sendMessage({
    sender: 'optionsPage',
    request: 'getData',
    details: { type },
  })

  if (articles.length !== rules.length) {
    return
  }

  const rule = getProperties(rules[ index ])

  exportRules({ [ type ]: [ rule ] })
}

const createExportAllButton = () => {
  const actions = document.querySelector('.help > div')

  if (actions.getElementsByClassName('export').length > 0) {
    return
  }

  const button = document.createElement('button')
  const text = document.createTextNode('Export all rules')

  button.appendChild(text)
  actions.prepend(button)

  button.classList.add('export', 'highlight-ok')

  button.addEventListener('click', () => handleExportAll())
}

const createExportButton = article => {
  if (article.getElementsByClassName('export').length > 0) {
    return
  }

  const span = document.createElement('span')
  const button = document.createElement('button')
  const text = document.createTextNode('Export')

  button.appendChild(text)
  span.appendChild(button)
  article.insertBefore(span, article.lastElementChild)

  button.classList.add('export', 'highlight-ok')

  button.addEventListener('click', () => handleExport(article))
}

const createExportButtons = () => {
  sections.forEach(section => {
    const articles = [ ...section.getElementsByTagName('article') ]

    articles.forEach(createExportButton)
  })
}

createExportAllButton()
createExportButtons()

const observer = new MutationObserver(createExportButtons)

observer.observe(main, { childList: true, subtree: true })
```

**Comment by nicko1337** [comment]
Can an import/export feature be officially added? The script solution works great but isn't very user friendly.

**Comment by Francewhoa** [comment]
Thanks for the script  dangkyokhoang :)

I agree with idkOnPop. I vote for adding this export/import to the add-on. So that users don't need to manually add this script.

Any volunteer for a patch? I would be happy to contribute testing and documentation if needed.

**Comment by dangkyokhoang** [comment]
I'll add this feature this week.

**Comment by dangkyokhoang** [comment]
Sorry, I has taken this into consideration and decided not to implement this feature. If something can be achieved using the rules themselves, I'd prefer not to add it to the extension.

Still I'm working on a feature similar to this, which enables users to share rules and add rules with a click.

**Comment by lollita** [comment]
Do you can add a option to "Export Rules" to export all the rules at once?

**Comment by dangkyokhoang** [comment]
I've edited the script in this comment https://github.com/dangkyokhoang/man-in-the-middle/issues/21#issuecomment-623853895 so that it creates a "Export all rules" button.

**Comment by lollita** [comment]
Work fine, ty.

**Comment by sergeevabc** [comment]
Aggrrhh, no “import/export all” by default drives me crazy.
By the way, the aforementioned script produces broken output in the console.
