### ISSUE TITLE
Changes won't save

### ISSUE THREAD

**Issue by t2YU2m8l83** [dangkyokhoang/Man-in-the-Middle#22]
Since a couple of days, when I change anything on the rules (edit/create/delete), after closing Firefox and reopening it, nothing has been saved. The rules I already added before are still there but I can no longer change them. I really don't know if this is a Firefox problem or an extension problem, but the last time I edited something back in mid July, it was saved. Since August it will no longer save. The other plugins (uMatrix, uBlock) still save their settings correct. I already took a look inside  the profiles folder but the only thing  I found for Man In The Middle were entries in storage-sync.sqlite file, but changes I made there directly, weren't Applied to the extension. Even deleting the entries resulted in no changes at all. The profile/storage folder also had nothing saved regarding Man In The Middle. Deactivating or reinstalling also had no effect. After reinstalling the extension, it even had all my old rules and not an empty rule set. How does this plugin save it's setting so I could at least change them manually?

**Comment by dangkyokhoang** [comment]
It uses `browser.storage.sync` to store rules.

Go to the Options page, open dev tools and you'll perhaps see some error messages when modifying rules. The cause of the issue might be that you've exceeded storage limit: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync. If it's because of the storage limit, try deleting some rules via the dev tools:
- `await browser.storage.sync.get()`
- Delete some rules
- `browser.storage.sync.set()`

**Comment by t2YU2m8l83** [comment]
It's really the storage limit error. But deleting rules definitely isn't an option. Isn't there any other way to extend the limit?

**Comment by dangkyokhoang** [comment]
I don't think it's possible to increase the limit, at least for now. I have the same problem but I can't do anything about it so I'm developing a new version of the extension that allows syncing via my server.

**Comment by t2YU2m8l83** [comment]
Syncing through a third-party server isn't really something I would like. I'm not familiar with the storage system for browser extensions, but can't you use profile/storage to store the settings? uMatrix an uBlock do the same thing and while I have turned sync in Firefox off, I highly doubt that the things they store there aren't synced.

**Comment by dangkyokhoang** [comment]
`storage.local` doesn't seem to have quotas, it just doesn't sync. I understand that most users of this extension might not want to upload their data to a third-party server so the default option will be `storage.local`, or `storage.sync` if they want their data to be synced.

**Comment by t2YU2m8l83** [comment]
`browser.storage.sync.set()` throws the following exception:
```
Uncaught Error: Incorrect argument types for storage.StorageAreaSync.set.
    <anonymous> debugger eval code:1

    throwError resource://gre/modules/Schemas.jsm:2505
    checkParameters resource://gre/modules/Schemas.jsm:2562
    stub resource://gre/modules/Schemas.jsm:2672
    <anonymous> debugger eval code:1
```
Is there any other way to fix this, so I can edit my rules again? How long do you think it will take until `storage.local` is implemented?

**Comment by dangkyokhoang** [comment]
Sorry, I intended to use the local storage in the next big update but it seems that it'll take a (very) long time for that update to be published. Since you're urgently in need of the local storage, I think there should be a minor update with that feature. This weekend, maybe.

**Comment by t2YU2m8l83** [comment]
That would be awesome, thank you!

**Comment by dangkyokhoang** [comment]
I've updated the extension with local storage support. Please check it out.
