### ISSUE TITLE
Default Local/Sync Options

### ISSUE THREAD

**Issue by t2YU2m8l83** [dangkyokhoang/Man-in-the-Middle#23]
Thank you for implementing the local storage system. It's interesting that you yourself even mentioned, that he majority of users for this addon would prefer not syncing with a third party server and now sync is the default value for all rules. I don't know how the syncing process works, but it wouldn't be a good move if you instantly sync everything after the update and give the user no choice to keep his rules for himself. Going through all the rules after the update and toggling the sync everywhere was also pretty annoying. Therefor I suggest, that you implement an option to choose if sync or local is default and somehow tell the user that sync happens trough 3rd party and only allow sync after he confirms that.

**Comment by dangkyokhoang** [comment]
There's some misunderstanding here. The syncing process is done by browser (Firefox / Mozilla), hence privacy and security. Here's the code that saves data to `storage.sync`:
https://github.com/dangkyokhoang/man-in-the-middle/blob/caceb023cd0a31a736de958a63ded9bd18f408bb/src/page/background/js/class/Storage.js#L31-L37

Syncing via a third-party service is just an idea that solves the `storage.sync` quota problem. If it will ever be made available, users can opt to use it, in an explicit manner, and it will never be the default option. So don't worry that your data will ever be unintentionally uploaded to a third party server. And you don't need to change all rules to "Local" if you're not running out of sync quota.

**Comment by t2YU2m8l83** [comment]
That's good to hear. But a toggle for the what's default would still be a good feature somewhere in the future.

**Comment by dangkyokhoang** [comment]
You can inject a content script to the extension's options page to change newly added rules to Local.

I want to keep the extension having no settings other than user's rules so I think this won't be added to the extension.
