### ISSUE TITLE
Readability rule

### ISSUE THREAD

**Issue by lollita** [dangkyokhoang/Man-in-the-Middle#25]
Do it is possible to create a rule to apply firefox readability internal to pages?

**Comment by dangkyokhoang** [comment]
Do you mean Firefox Reader View? It seems that it's not possible at the moment. See https://bugzilla.mozilla.org/show_bug.cgi?id=1371786 for more information.

**Comment by lollita** [comment]
Do it is possible to import Script
"resource://gre/modules/reader/Readability.js"
direclty withou copy it in webextension profile,
and then use it?

**Comment by dangkyokhoang** [comment]
No. Web pages can't load such resources but you can get one from jsDelivr https://www.jsdelivr.com/package/npm/moz-readability and inject it to pages using content script:
``` javascript
const lib = document.createElement('script')
lib.src = 'https://cdn.jsdelivr.net/npm/moz-readability@0.2.1/Readability.min.js'
document.body.appendChild(lib)
```

**Comment by lollita** [comment]
> Do you mean Firefox Reader View? It seems that it's not possible at the moment. See https://bugzilla.mozilla.org/show_bug.cgi?id=1371786 for more information.

I not will to "Allow content scripts on reader mode pages" I will simulate the Readibility button click when url match a rule.

**Comment by dangkyokhoang** [comment]
> ```js
> const lib = document.createElement('script')
> lib.src = 'https://cdn.jsdelivr.net/npm/moz-readability@0.2.1/Readability.min.js'
> document.body.appendChild(lib)
> ```

Have you tried this?

**Comment by lollita** [comment]
I would the Firefox builded action.

**Comment by dangkyokhoang** [comment]
> I would the Firefox builded action.

I don't quite understand this.

I suppose that you want to enable Reader view for some pages using content script? To do that, you need to [copy the Readability.js script and] inject the Readability.js into the desired pages and then parse the pages. If you don't want to copy the script, and instead want to inject the script by URL, you have to inject the script via the DOM (creating a script element, assigning the URL, injecting it to the `document`). Note that injecting a script to pages via the DOM might not work if a strict CSP prevents that. You might want to consult the documentation at https://github.com/mozilla/readability.

**Comment by lollita** [comment]
I would man-in-the-middle do as [this addon](https://addons.mozilla.org/en-US/firefox/addon/automatic-reader-view/).

**Comment by dangkyokhoang** [comment]
![Inject script - Man in the Middle](https://user-images.githubusercontent.com/14311741/152833735-24228b5b-df3f-4ec2-b9f5-79d6dff247be.png)

This might be your best bet.

P/s: This is the best I can help. My previous comments should've provided enough information.

**Comment by lollita** [comment]
Do it is possible to toggle it on page refresh?
