### ISSUE TITLE
requestHeaders and responseHeaders object together

### ISSUE THREAD

**Issue by lollita** [dangkyokhoang/Man-in-the-Middle#26]
I would to set the reponseHeader as a function of requestHeader.
Do it is then possible to have the requestHeaders object also in responseHeaders modify request type ?

**Comment by dangkyokhoang** [comment]
You can't access request headers in response header rules but you can store request headers in `context`. It's something like this:
![image](https://user-images.githubusercontent.com/14311741/96535280-a1f05a80-12bb-11eb-8aa8-8ac5bd2a25ec.png) ![image](https://user-images.githubusercontent.com/14311741/96535319-b7658480-12bb-11eb-98ba-2179b2b2c175.png)

`context` is shared between JavaScript rules and persists until you close the browser.
