### ISSUE TITLE
X-Frame-Options not fire

### ISSUE THREAD

**Issue by lollita** [dangkyokhoang/Man-in-the-Middle#27]
{"headerRules":[{"name":"X-Frame-Options","urlFilters":["https://www.radioradicale.it"],"originUrlFilters":[],"method":"GET","textType":"plaintext","textHeaders":"x-frame-options:\ncontent-security-policy:","headerType":"responseHeaders"}]}

Why not work?
With other sites it work.

**Comment by dangkyokhoang** [comment]
It actually works. `Ctrl + F5` might fix the problem.

The reason it doesn't work for you might be that the site uses `cache-control: public, max-age=120` for the document (HTML). Browser caches the response, including the response headers. The browser then serves the cached, unmodified version of the response headers.

**Comment by lollita** [comment]
With Ctrl + F5 it works but I load the link in a iFrame with button action.
I tryed to add +"#"+(new Date()).getTime() to link or add header cache-control:max-age=0 but not work.
Do it is possible to add a way to force enforcement of the rules?

I add that now i see that the same pae with iframe work fine in file:///
but still not work in web extension moz-extension://

the url that I use in iFrame is https://www.radioradicale.it/palinsesto that have a redirect.

**Comment by dangkyokhoang** [comment]
Try this rule:
``` javascript
(e=>{Object.entries(e).forEach(([e,t])=>t.forEach(async t=>{const{id:n,enabled:s,sync:r}=await Runtime.sendMessage({sender:"optionsPage",request:"add",details:{type:e}});await Runtime.sendMessage({sender:"optionsPage",request:"modify",details:{type:e,id:n,change:t}}),Collection.create(e,{id:n,enabled:s,sync:r,...t})}))})({"headerRules":[{"name":"Radio Radicale","urlFilters":["https://www.radioradicale.it/"],"originUrlFilters":[],"method":"GET","textType":"plaintext","textHeaders":"cache-control:\nx-frame-options:","headerType":"responseHeaders"}]});
```

**Comment by lollita** [comment]
Not solve.
I had already tried too cache-control:
The problem is when the rule apply to a webextension html page.
But for other sites it apply However.

**Comment by dangkyokhoang** [comment]
Well, it works for me. Firefox 82, on Windows and Linux :thinking: 
![image](https://user-images.githubusercontent.com/14311741/97040331-f9cae200-1597-11eb-836f-bcebefb25115.png)

I think I can't help you any further on this so I'm closing this.
