### ISSUE TITLE
Modify request body (POST)

### ISSUE THREAD

**Issue by pintassilgo** [dangkyokhoang/Man-in-the-Middle#33]
Would it be possible?

Thanks.

**Comment by dangkyokhoang** [comment]
It's not possible to implement a method that covers all cases. However, you might be able to achieve what you want with Content Script and/or Response Rule. These are some cases:
- If the site uses basic form submit (form being submitted naturally), use a Content Script to add a listener to the 'submit' event of the form. You can change form values from inside the listener.
- If the site uses a listener to submit the form, set `DOM event` to `Loading` and add a capturing listener to `window` and your listener will likely be called before the site's listener.
- If the site uses a listener to submit the form and you want to change the values from inside their listener, you might want to use a Response Rule to override their script.
- If the request is sent via `XMLHttpRequest` or `fetch`, set `DOM event` to `Loading` and insert a script element to the document, in which you override `window.XMLHttpRequest` or `window.fetch` with your own implementation that modifies request body being sent.

**Comment by pintassilgo** [comment]
Thanks for the detailed answer.

Can't `onBeforeRequest` change requestBody? It has `details.requestBody`...

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest

**Comment by dangkyokhoang** [comment]
No. Request body is read-only.
