### ISSUE TITLE
Can I do this with your repo?

### ISSUE THREAD

**Issue by zydjohnHotmail** [dangkyokhoang/Man-in-the-Middle#36]
Hello:
Your repo looks good.  I will spend more time to study it.
Now, I have one more tricky question.
If you have ever shopped in https://www.amazon.com/, you know that you can shop many items in different category, and finally, check out when you done, then pay the total bills in one place.
There is a similar web site, there are about 3 children pages, just like different categories in Amazon, I have to visit each of the 3 pages, and select one item from each page, each have about 100 items, then click a button to check out or submit the form (HTTP Post).
What I want to do is: I want to use your repo to create one total page, in which all the 3 children pages are inside this total page, also add some additional JavaScript, so I can select one item from each page, and submit the form.
In short, the only thing to do differently is: in stead of visiting one page 3 times, I want to merge all 3 pages to make one page.  The advantage is: I don’t have to visit so many different pages, I can stay in the total page.
The old way of data flow is like this:
A. visit https://www.child_page1.com/, click to select item #1,
B. visit https://www.child_page2.com/, click to select item #2,
C. visit https://www.child_page3.com/, click to select item #3,
D. click a submit form button under the last item #3, then submit the form.
What I want to do now is:
A. Create a frame of a total page,
B. Load https://www.child_page1.com/ and append it as one HTML element. (I think maybe Jquery parseHTML can add an array of DOM objects inside one element, like DIV)
C. Load https://www.child_page2.com/ and append it as one HTML element. (I think maybe Jquery parseHTML can add an array of DOM objects inside one element, like DIV)
D. Load https://www.child_page3.com/ and append it as one HTML element. (I think maybe Jquery parseHTML can add an array of DOM objects inside one element, like DIV)
E. From each newly added elements, pick up one element, and finally submit the form.  In other words, I want to make one big DOM includes all 3 children pages, then I can use JavaScript to select DOM nodes, like: getelementsbyclassname, and then click on the selected DOM nodes, and finally click on the submit form button.
There are a few other additional JavaScripts, work like adding items to shopping cart, and finally submit the form using HTTP Post.
Give me some ideas, if I can reach my goal with your repo.?
If yes, then provide some rules for making the total page, where I can add other 3 different pages into it.
If not directly, then give me some ideas on how I can do this with JavaScript/Jquery?
Thanks,

**Comment by dangkyokhoang** [comment]
It's possible but it's quite hard if you're new to JS. An easier method is to find their APIs / requests and send from your application.

**Comment by zydjohnHotmail** [comment]
Hello:
I have some experience with JS, about 2 years, but I need some instructions to use your repo., if it is possible.  Give me some detailed instructions. 
Thanks,

**Comment by dangkyokhoang** [comment]
Here's the full documentation: https://github.com/dangkyokhoang/man-in-the-middle
