### ISSUE TITLE
Q: CSP allow CSS injection

### ISSUE THREAD

**Issue by atomGit** [dangkyokhoang/Man-in-the-Middle#37]
i want to allow css injection globally and am wondering if this is correct...

text headers: `content-security-policy: style-src`
text type: plain text
header type: response
url filters: `*`
method: delete
origin url filters: [empty]

**Comment by dangkyokhoang** [comment]
Injecting CSS from the extension's side should work for every site, without the need for Header Rule.

**Comment by atomGit** [comment]
i remember i wasn't able to inject css on a server that set Content Security Policy header `style-src` until i removed the header (i don't recall the site address)

granted there are not allot of sites that prevent css injection, but some do and since CSP is handled browser-side (i think?), the browser won't permit injection

**Comment by dangkyokhoang** [comment]
Web extensions bypass sites' CSP policies. You only need to override the CSP header if you inject CSS to a page with a `<link>` or `<style>` element, using `document.createElement('link'); document.appendChild(...)` for example.
