### ISSUE TITLE
Q: redirect with RegEx

### ISSUE THREAD

**Issue by atomGit** [dangkyokhoang/Man-in-the-Middle#38]
trying to do a text redirect with RegEx and capture group

this works fine...

```
http://a.com/
http://b.com/
```

but these don't for some reason...

```
http://a.com/(.*)
http://b.com/$1

http://a.com/(.*)
http://b.com/\1

http:\/\/a\.com\/(.*)
http://b.com/$1
```

firefox 87.*
mitm: 5.4.3

**Comment by dangkyokhoang** [comment]
Regex starts and ends with `/`. Try `/http:\/\/a\.com\/(.*)/` -> `http://b.com/$1`.

**Comment by atomGit** [comment]
ah ha - ok - you might want to update the readme : [Text redirect URL](https://github.com/dangkyokhoang/man-in-the-middle#text-redirect-url)

thanks

also, the replace expression works without a trailing dot, but i'll leave it in there

thanks again

**Comment by dangkyokhoang** [comment]
I think it's correctly documented :/

**Comment by atomGit** [comment]
yes it is, sorry - you ended your example with a period (`http://b.com/$1.`) and i interpreted it to mean the dot had to follow the replacement
