### ISSUE TITLE
feature: wildcard redirects

### ISSUE THREAD

**Issue by atomGit** [dangkyokhoang/Man-in-the-Middle#39]
for simpler redirects that don't require full RegEx, it would be great to be able to use wildcards 

so this...

`/http:\/\/example\.com\/(.+)/(.*)/`

becomes this...

`http://example.com/*/*`

replacements are the same...

`http://somesite.com/$1/$2/somedirectory`

**Comment by dangkyokhoang** [comment]
No, sorry. That introduces more complexity to users. Writing a regex should be easier (and funnier) than having to remember a new syntax just to redirect some requests.
