### ISSUE TITLE
Origin URL filters not end fail

### ISSUE THREAD

**Issue by lollita** [dangkyokhoang/Man-in-the-Middle#42]
to filter in blocking rules url that not end with "/end/" I use in Origin URL filters:
/(?<!\/end\/)$/
but not work, why?

**Comment by dangkyokhoang** [comment]
You must escape `/` with `\`:
```
/(?<!\/end\/)$/
```

**Comment by lollita** [comment]
I forgot escape / but also /(?<!\/end\/)$/ It doesn't seem to work.
also
!/end/
!/\/end\/$/

**Comment by dangkyokhoang** [comment]
Try this. It should block https://example.com/ but not https://example.com/end/.
![Man in the Middle extension - Block requests](https://user-images.githubusercontent.com/14311741/126369082-cff1de7d-5621-45c4-9c04-f76cbb773333.png)

**Comment by lollita** [comment]
It work but, why if I use
redirect: $1/end/
Origin URL filters: /\/end\/$/
not work?
