### ISSUE TITLE
Request: Enable JS injection into an extension

### ISSUE THREAD

**Issue by silverma** [dangkyokhoang/Man-in-the-Middle#45]
Hi - thanks for making this extension available - it's great!

I'd also like to use it to inject some JS into an extension, with a URL like "chrome-extension://", but that doesn't seem to work. Is there a way to enable man-in-the-middle to work on an extension page as well?

**Comment by dangkyokhoang** [comment]
Afaik, no, you cannot inject JS into extension pages on Chrome. On Firefox, an extension can inject JS to its own pages, but not others'.

**Comment by silverma** [comment]
Ok, thank you for the response!
