### ISSUE TITLE
Crashing in newer versions

### ISSUE THREAD

**Issue by gdl-blue** [dangkyokhoang/Man-in-the-Middle#48]
It works in Firefox 73, but not on 78esr.

**Comment by dangkyokhoang** [comment]
Can you provide a minimal reproduction of the issue? What is the type of the rule that breaks? I've done some tests and found it working on Firefox 78esr.

**Comment by gdl-blue** [comment]
ahh, I think it was my browser's problem. I downgraded and re-upgraded Firefox and it works. sorry.
