### ISSUE TITLE
Exclude Pattern field

### ISSUE THREAD

**Issue by dangkyokhoang** [dangkyokhoang/Man-in-the-Middle#5]
> -Regex Negative Lookbehinds `(?<!)` don't work
> -An "Exclude Pattern" field would be great and make the Negative Lookbehind problem obsolet. It's pretty usefull for conditional rules `if url == google.com && !url.contains("q=") do redirect("google.com?q=test")`

_Originally posted by @t2YU2m8l83 in https://github.com/dangkyokhoang/Man-in-the-Middle/issues/3#issuecomment-439410109_

**Comment by dangkyokhoang** [comment]
Does something like this sound good?
````
goole.com
!q=
````
matches `google.com` except URLs containing `q=`
````
://
!google.com
!/b.ng\.com/
````
matches all URLs except URLs containing `google.com` and URLs matching `/b.ing\.com/`.

Does it make `URL filters` become complicated or confused? Coz I wanna avoid adding fields as much as possible.

**Comment by t2YU2m8l83** [comment]
That should work as long as it is mentioned in the documentation.

**Comment by dangkyokhoang** [comment]
3.2 released. Exclude patterns are made possible.
> A `URL` is satisfied if it matches at least one of the filters and DOES NOT match any `URL exception`.

**Comment by t2YU2m8l83** [comment]
Works, thanks.
