### ISSUE TITLE
Simple redirect example

### ISSUE THREAD

**Issue by sergeevabc** [dangkyokhoang/Man-in-the-Middle#51]
Dear @dangkyokhoang, no doubt Man in the middle is a very powerful addon, but its documentation leaves much to be desired because it lacks real life examples. 

For example, I want to do one of the simplest imaginable things: redirect requests from one domain to another. The following setup (see screenshot) does not work, why?

![image](https://user-images.githubusercontent.com/373718/201322024-97f0a4d7-b564-4d35-9e7f-1c28f194fc9f.png)

**Comment by dangkyokhoang** [comment]
`Text redirect URL` must be an absolute URL, such as https://github.com/.
