### ISSUE TITLE
Better function to edit headers

### ISSUE THREAD

**Issue by dangkyokhoang** [dangkyokhoang/Man-in-the-Middle#6]
> -A better function to edit headers:
> 
> ```
> requestHeaders.AddOrOverride(Name, Value){
> var existingHeader = requestHeaders.find(({name}) => (
> name.toLowerCase() === Name.toLowerCase()
> ));
> 
> if (existingHeader === undefined){
> requestHeaders.push({name: Name,value: Value});
> }
> else{
> existingHeader.value = Value;
> }
> }
> ```

_Originally posted by @t2YU2m8l83 in https://github.com/dangkyokhoang/Man-in-the-Middle/issues/3#issuecomment-439410109_

**Comment by dangkyokhoang** [comment]
The extension does something like this. See [the doc](https://github.com/dangkyokhoang/Man-in-the-Middle#text-headers) or [the source code](https://github.com/dangkyokhoang/Man-in-the-Middle/blob/e1bb2de21135b738793b9be2f0da736d74677f35/src/page/background/js/class/HeaderRule.js#L51) for this.
Have I understood your comment?

**Comment by t2YU2m8l83** [comment]
I'd like to have this function as an extension for requestHeaders/responseHeaders arrays available in the javascript manipulation type. instead of this code:

```
var ips = {us:"65.61.106.131", ru:"89.109.194.164", jp:"202.173.111.135",
 gb:"80.253.127.23", cn:"61.139.191.39", br:"177.154.223.45",
fr:"194.98.63.127", de:"83.97.23.105"};

var existingHeader = requestHeaders.find(({name}) => (
name.toLowerCase() === 'x-forwarded-for'
));

if (existingHeader === undefined){
requestHeaders.push({name: 'X-Forwarded-For',value: ips["jp"]});
}
else{
existingHeader.value = ips["jp"];
}
return requestHeaders;
```

I'd like to use something like this:

```
var ips = {us:"65.61.106.131", ru:"89.109.194.164", jp:"202.173.111.135",
gb:"80.253.127.23", cn:"61.139.191.39", br:"177.154.223.45",
fr:"194.98.63.127", de:"83.97.23.105"};

requestHeaders.AddOrUpdate('X-Forwarded-For', ips["jp"]);
return requestHeaders;
```

This would decrease code repetitions significant if I want to add headers through javascript.

**Comment by dangkyokhoang** [comment]
I'll think of it. If there's an update on this, you'll be notified.

Anyway, as you may know for sure the list of headers sent by the browser by using `devtools > Network`, and the devtools Network also displays modified headers, there's no need to check if a header exists using js.
Until there's a change on this, your code should be something like this:
````JavaScript
const ips = {us:"65.61.106.131", ru:"89.109.194.164", jp:"202.173.111.135",
gb:"80.253.127.23", cn:"61.139.191.39", br:"177.154.223.45",
fr:"194.98.63.127", de:"83.97.23.105"};
// You know that the header `X-Forwarded-For` is not sent by your browser by default,
// so you just add one.
requestHeaders.push({name: 'X-Forwarded-For', value: ips["jp"]});
return requestHeaders;
````
Or this:
````JavaScript
// You know that the header `Accept-Language` is sent by your browser by default,
// so you just modify the existing header
requestHeaders.find(({name}) => name.toLowerCase() === 'accept-language').value = 'ja';
return requestHeaders;
````

**Comment by t2YU2m8l83** [comment]
Technically I should know about this but in general I'm programing safe and if my random ip rule is still active (because I forgot to deactivate it) the code without checks wouldn't do the trick.

**Comment by dangkyokhoang** [comment]
Ok. It'll be something like this, maybe:
````JavaScript
// 1 header
requestHeaders.modify([ ['X-Forwarded-For', ips['jp']] ]);
// 2 headers
requestHeaders.modify([
    ['X-Forwarded-For', ips['jp']],
    ['Accept-Language', '*'],
]);
````

**Comment by dangkyokhoang** [comment]
3.2 released. The method name is `modify` (`requestHeaders.modify`, `responseHeaders.modify`). Note that this may not work properly if there are multiple headers with the same name (e.g: `Set-Cookie`).

**Comment by t2YU2m8l83** [comment]
Works, thanks.
