### ISSUE TITLE
JQuery support

### ISSUE THREAD

**Issue by t2YU2m8l83** [dangkyokhoang/Man-in-the-Middle#8]
It would be greate if Content Scripts and Javascript rules could use JQuery even if the side I'm injecting the Content Script into doesn't implement it.

**Comment by dangkyokhoang** [comment]
You can easily achieve this by placing the this rule on top of the other rules. If something's not working, set the `DOM event` to `Loaded`. Other libraries, including your custom ones, can be injected to pages like this.
![image](https://user-images.githubusercontent.com/14311741/48668674-23ff0400-eb26-11e8-87fe-43a1bff9624d.png)
Improvements like your suggestions on the issue https://github.com/dangkyokhoang/Man-in-the-Middle/issues/7 can also be achieved by scripts injected to the extension's options page. The black theme you see in the image is an example. However I choose to feature them coz they cost nothing but improve UX. jQuery support is different as it may degrade browser perf and users still need to insert their specific version of jQ if it's not supported.

**Comment by t2YU2m8l83** [comment]
The code from your image doesn't work for me. I tried different dom events and placing the code at the top of the same rule where I need it but nothing happend. I'm not really good in js but in the `/*! */` part is not a single link to an actual js file, why should this even work then? Somthing I should point out her, I use uMatrix to disable js and your plugin can still run the content scripts (which is great and I really appreciate it), could this maybe be the problem here?

**Comment by dangkyokhoang** [comment]
You need to get a production version of jQ and put it in the `Code` field. Here's the version I found on jQ home page [https://code.jquery.com/jquery-3.3.1.min.js](https://code.jquery.com/jquery-3.3.1.min.js). In the image, you see only some first characters of the code as overflowed texts aren't in view.

**Comment by t2YU2m8l83** [comment]
Now it works, thanks. Not really a slick solution but I can work with it.
