### ISSUE TITLE
How to remove the HTTPONLY attribute 

### ISSUE THREAD

**Issue by dinh** [dangkyokhoang/Man-in-the-Middle#9]
How to remove the HTTPONLY attribute  from a cookie ?

**Comment by dangkyokhoang** [comment]
Use a Header Rule to remove the `HttpOnly` flag from `Set-Cookie` headers:
````JavaScript
responseHeaders.forEach(header => {
    if (header.name.toLowerCase() === 'set-cookie') {
        header.value = header.value.split(';')
            .filter(pair => pair.trim().toLowerCase() !== 'httponly')
            .join('; ');
    }
});
return responseHeaders;
````
This is the original `Set-Cookie` header:
![Modify cookie](https://user-images.githubusercontent.com/14311741/48978746-e4668800-f0e2-11e8-912f-663d95066b10.png)
And this is what we get:
![Modify cookie - Remove HttpOnly flag from cookie](https://user-images.githubusercontent.com/14311741/48978706-2b07b280-f0e2-11e8-8043-925ca99d42b0.png)
![Modify cookie - Remove HttpOnly flag from cookie](https://user-images.githubusercontent.com/14311741/48978722-686c4000-f0e2-11e8-869d-64b58d37cefa.png)

**Comment by dinh** [comment]
It works! Thank you for your prompt answer and for this great extension. I am playing with all the features and loving it so far.

**Comment by dangkyokhoang** [comment]
Thank you for your interest in the extension. I hope you'll share it to your friends. If you have more questions, open new [issues](https://github.com/dangkyokhoang/Man-in-the-Middle/issues) or direct message me via [Facebook](https://www.facebook.com/dangkyokhoang).
